config/routes.rb
MelodyNelson::Application.routes.draw do
  get "gallery/index"
  get "gallery/editimages"
  get "gallery/edit"
  get "gallery/update"
  get "gallery/new"
  get "gallery/create"
  get "gallery/destroy"
  get "contacts/index"
  get "contacts/new"
  get "contacts/create"
  get "contacts/edit"
  get "contacts/update"
  get "contacts/destroy"
  get "events/index"
  get "events/update"
  get "events/new"
  
  root to: "contacts#index"
  match "login" => "user_sessions#new", via: [:get, :post]
  
  resources :events, :path => "events"
  resources :contacts, :path => "contacts"
  resources :gallery, :path => "gallery"
  resources :photos, :path => "gallery"
  resources :user_sessions
  resources :users
  resources :menus, :path => "menus"

end

app/models/user.rb
class User < ActiveRecord::Base
	acts_as_authentic
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :require_user, :only => [:index, :show, :edit, :update, :new, :create]
  
  def index
  	  if current_user.is_admin==0
  	  	  flash[:notice]="Only admins can see this page"
  	  	  redirect_to root_url
  	  else
  	  	  @users = User.all
  	  end
  end  

  
	
  def new
        if(current_user.is_admin==1)
  	  	@user = User.new
  	else 
  		flash[:notice]="Only admin users can add new users"
  		redirect_to root_url
  	end
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "User created"
      redirect_back_or_default root_url
    else
      flash[:notice] = "User not created"
      render :action => :new
    end
  end
  
  def show
    	    @user = current_user
  end

  def edit
    if current_user.is_admin==1
    	    @user = User.find(params[:id])
    else
    	    @user = current_user
    end
  end
  
  def update
    if current_user.is_admin==1
    	    @user = User.find(params[:id])
    else
    	    @user = current_user
    end
    if @user.update_attributes(user_params)
      flash[:notice] = "User updated!"
      redirect_to root_url
    else
      render :action => :edit
    end
  end
  
  def destroy
  	if current_user.is_admin==1
  	  	@user = User.find(params[:id])
  	  	if @user==current_user
  	  		flash[:notice]="Can't delete yourself"
  	  	else
  	  		if @user.destroy
  	  			flash[:notice]="User successfully deleted"
  	  		else
  	  			flash[:notice]="Error! Could not delete user"
  	  		end
		end
		redirect_to action: "index"
  	else
  		flash[:notice]="Only admins can delete users"
		redirect_to root_url
  	end
  end
  
  private

  def user_params
    params.require(:user).permit(:login, :email, :password, :password_confirmation, :is_admin)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div id="header">Edit User</div>
<div class="form">
<%= form_for @user do |f| %>
  <% if current_user.is_admin==1 %>
	  <%= f.label :login %><br />
	  <%= f.text_field :login %><br />
	  <br />
  <% end %>
  <%= f.label :email %><br />
  <%= f.text_field :email %><br />
  <br />
  <%= f.label :password %><br />
  <%= f.password_field :password %><br />
  <br />
  <%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation %><br />
  <br />
  <% if current_user.is_admin==1 %>
	  <%= f.label :is_admin %><br />
	  <%= f.check_box :is_admin %><br />
	  <br />
  <% end %>
  <%= f.submit "Edit" %>
<% end %>
</div>

app/views/users/index.html.erb
<div id="header">All users</div>
<div class="linkedit">
	<%= link_to "Add new user", action: "new" %>
</div>
<div class="form">
<% @users.each do |u| %>
	<%= "Login name: "+u.login %><br />
	<%= "Email: "+u.email %><br />
	<%= link_to "Edit", edit_user_path(u) %>
	<%= link_to "Delete", user_path(u), method: "delete", data: { confirm: 'Are you sure?'} %><br /><br />
<% end %>
</div>
	

app/views/users/new.html.erb
<div id="header">Add User</div>
<div class="form">
<%= form_for @user, :url => users_path do |f| %>
  <%= f.label :login %><br />
  <%= f.text_field :login %><br />
  <br />
  <%= f.label :email %><br />
  <%= f.text_field :email %><br />
  <br />
  <%= f.label :password %><br />
  <%= f.password_field :password %><br />
  <br />
  <%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation %><br />
  <br />
  <%= f.label :is_admin %><br />
  <%= f.check_box :is_admin %><br />
  <br />
  <%= f.submit "Add User" %>
<% end %>
</div>