config/routes.rb
MelodyNelson::Application.routes.draw do
  get "gallery/index"
  get "gallery/editimages"
  get "gallery/edit"
  get "gallery/update"
  get "gallery/new"
  get "gallery/create"
  get "gallery/destroy"
  get "contacts/index"
  get "contacts/new"
  get "contacts/create"
  get "contacts/edit"
  get "contacts/update"
  get "contacts/destroy"
  get "events/index"
  get "events/update"
  get "events/new"
  
  root to: "contacts#index"
  match "login" => "user_sessions#new", via: [:get, :post]
  
  resources :events, :path => "events"
  resources :contacts, :path => "contacts"
  resources :gallery, :path => "gallery"
  resources :photos, :path => "gallery"
  resources :user_sessions
  resources :users
  resources :menus, :path => "menus"

end

app/models/event.rb
class Event < ActiveRecord::Base
	has_attached_file :image,
		:styles => {:medium => "x140"}
		#:url => '/images/events/:id/:style/:basename.:extension',
		#:path => ':rails_root/public/images/events/:id/:style/:basename.:extension'
		
	validates :headline, presence: true
	validates :time, presence: true
	validates_attachment_content_type :image, :content_type => ['image/jpeg', 'image/png', 'image/gif']
	validates_attachment_size :image, :less_than =>  5.megabytes
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	before_filter :require_user, :only => [:new, :create, :edit, :update, :destroy]
  def index
  	  @events=Event.paginate(:page => params[:page], :per_page => 3).order('time DESC')
  end

  def edit
  	  @event=Event.find(params[:id])
  end
  
  def update
  	  @event=Event.find(params[:id])
  	  if request.patch?
  	  	  parameters=event_params
  	  	  parameters.delete(:image) if params[:event][:image].blank?
  	  	  if @event.update_attributes(parameters)
  	  	  	  flash[:notice]="Event successfully updated"
  	  	  else
  	  	  	  flash[:notice]="Error! Could not update event"
  	  	  end
  	  	  redirect_to action: "index"
  	  end
  end

  def destroy
  	  @event = Event.find(params[:id])
  	  if @event.destroy
  	  	  flash[:notice]="Event successfully deleted"
  	  else
  	  	  flash[:notice]="Error! Could not delete event"
  	  end
  	  redirect_to action: "index"  	  
  end

  def new
  	  @event=Event.new	  	  
  end
  def create
  	  if request.post?
  	  	  @event = Event.new(event_params)
  	  	  if  @event.save
  	  	  	  flash[:notice]="Event successfully added"
  	  	  else
  	  	  	  flash[:notice]="Error! Could not add event"
  	  	  end
  	  	  redirect_to action: "index"
  	  end
  end
  
  private
  def event_params
  	  params.require(:event).permit(:headline, :description, :time, :image)
  end
  
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/edit.html.erb
<div id="header">Edit event</div>
<div class="linkedit">
	<%= link_to "Back", events_path %>
</div>
<div class="form">
<%= form_for @event, :html => {:multipart => 'true'} do |e| %>
	<table>
	<tr><td>Headline:</td><td><%= e.text_field :headline %></td></tr>
	<tr><td>Description:</td><td><%= e.text_area :description, size: "60x12" %></td></tr>
	<tr><td>Date and time:</td><td><%= e.datetime_select :time %></td></tr>
	<tr><td>Image:</td><td><%= e.file_field :image %></td></tr>
	<tr><td><%= e.submit "Update" %></td></tr>
	</table>
<% end %>
</div>

app/views/events/index.html.erb
<div id="header">Events</div>
<div class="linkedit">
	<% if current_user_session %>
		<%= link_to "New event", action: "new" %>
	<% end %>
</div>

<% @events.each do |e| %>
	<div class="event">
	<% if e.image_file_name %>
		<%= image_tag e.image.url(:medium) %>
	<% else %>
		<%= image_tag "logo.jpg" %>
	<%end%>
	<div class="eventhead"><%=e.headline %></div>
	<div class="eventtime"><%= e.time.in_time_zone('Berlin').strftime("%A, %d. %m. %y, %H:%M h.") %></div>
	<p>
	<%= e.description.gsub(/\n/, '<br/>').html_safe %><br/>
	<% if current_user_session %>
		<%= link_to "Update", edit_event_path(e) %>
		<%= link_to "Delete", event_path(e), method: "delete", data: { confirm: 'Are you sure?'} %>
	<% end %>
	</p>
	</div>
<% end %>
<div class="paginate"><%= will_paginate @events, :page_links => false, :previous_label => "< Newer", :next_label => "Older >" %></div>

app/views/events/new.html.erb
<div id="header">Add new event</div>
<div class="linkedit">
	<%= link_to "Back", events_path %>
</div>
<div class="form">
<%= form_for @event, :html => {:multipart => 'true'} do |e| %>
	<table>
	<tr><td>Headline:</td><td><%= e.text_field :headline %></td></tr>
	<tr><td>Description:</td><td><%= e.text_area :description, size: "60x12" %></td></tr>
	<tr><td>Date and time:</td><td><%= e.datetime_select :time %></td></tr>
	<tr><td>Image:</td><td><%= e.file_field :image %></td></tr>
	<tr><td><%= e.submit "Create" %></td></tr>
	</table>
<% end %>
</div>