config/routes.rb
MelodyNelson::Application.routes.draw do
  get "gallery/index"
  get "gallery/editimages"
  get "gallery/edit"
  get "gallery/update"
  get "gallery/new"
  get "gallery/create"
  get "gallery/destroy"
  get "contacts/index"
  get "contacts/new"
  get "contacts/create"
  get "contacts/edit"
  get "contacts/update"
  get "contacts/destroy"
  get "events/index"
  get "events/update"
  get "events/new"
  
  root to: "contacts#index"
  match "login" => "user_sessions#new", via: [:get, :post]
  
  resources :events, :path => "events"
  resources :contacts, :path => "contacts"
  resources :gallery, :path => "gallery"
  resources :photos, :path => "gallery"
  resources :user_sessions
  resources :users
  resources :menus, :path => "menus"

end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	before_filter :require_user, :only => [:new, :create, :edit, :update, :destroy]
	
  def index
  	  @contact=Contact.first	  	  
  end

  def new
  	  if @contact=Contact.first
  	  	  flash[:notice]="Contact information has been added already. You can edit or reset it."
  	  	  redirect_to action: "index"
  	  else
  	  	  @contact=Contact.new
  	  end
  end

  def create
  	  if request.post?
  	  	  @contact = Contact.new(contact_params)
  	  	  if  @contact.save
  	  	  	  flash[:notice]="Contact information successfully added"
  	  	  else
  	  	  	  flash[:notice]="Error! Could not add contact information"
  	  	  end
  	  	  redirect_to action: "index"
  	  end
  end

  def edit
  	  @contact=Contact.find(params[:id])
  end

  def update
    	  @contact=Contact.find(params[:id])
  	  if request.patch?
  	  	  if @contact.update(contact_params)
  	  	  	  flash[:notice]="Contact information successfully updated."
  	  	  else
  	  	  	  flash[:notice]="Error! Could not update contact information."
  	  	  end
  	  	  redirect_to action: "index"
  	  end	  
  end

  def destroy
  	  @contact = Contact.find(params[:id])
  	  if @contact.destroy
  	  	  flash[:notice]="Contact information successfully reset."
  	  else
  	  	  flash[:notice]="Error! Could not reset contact information"
  	  end
  	  redirect_to action: "index"  	
  end
  
  private
  def contact_params
  	  params.require(:contact).permit(:name, :address, :phone, :email, :opening_hours, :facebook)
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/edit.html.erb
<div id="header">Edit contact</div>
<div class="linkedit">
	<%= link_to "Back", contacts_path %>
</div>
<div class="form">
<%= form_for @contact do |c| %>
	<table>
		<tr><td>Name:</td><td><%= c.text_field :name %></td></tr>
		<tr><td>Address:</td><td><%= c.text_field :address %></td></tr>
		<tr><td>Phone:</td><td><%= c.text_field :phone %></td></tr>
		<tr><td>Email:</td><td><%= c.text_field :email %></td></tr>
		<tr><td>Opening hours:</td><td><%= c.text_field :opening_hours %></td></tr>
		<tr><td>Facebook:</td><td><%= c.text_field :facebook %></td></tr>
		<tr><td><%= c.submit "Update" %></td></tr>
	</table>
<% end %>
</div>

app/views/contacts/index.html.erb
<% if @contact %>
		 
		<div id = "contact" >
		
		<div class = "contactinfo">
		<h2><%=@contact.name.upcase %></h2>
		<p>
		<%= @contact.address %><br/><br/>
		<%= @contact.phone.upcase %><br/><br/>
		<%= @contact.email %><br/><br/>
		<%= "Open " + @contact.opening_hours %><br/><br/>
		Find us on:<br/>
		<%= link_to image_tag('facebook_white.png') + "| Facebook", @contact.facebook, :style=> "float: left;", :target=>"_blank" %>
		<%= link_to image_tag('googlemaps.png') + "| Google maps", "http://maps.google.com?q=" + @contact.address, :style=> "float: right;", :target=>"_blank" %><br/>
		<% if current_user_session %>
			<br/><br/>
			<%= link_to "Update contact info", edit_contact_path(@contact) %>
			<%= link_to "Reset contact info", contact_path(@contact), method: "delete", data: { confirm: 'Are you sure?'} %>
		<% end %>
		</p>
		</div>
<% else %>
	<p> You haven't added any contact information to the site</p></br>
	<%= link_to "Add contact information", action: "new" %>
<% end %>
	

app/views/contacts/new.html.erb
<div id="header">New contact</div>
<div class="linkedit">
	<%= link_to "Back", contacts_path %>
</div>
<div class="form">
<%= form_for @contact do |c| %>
	<table>
	<tr><td>Name:</td><td><%= c.text_field :name %></td></tr>
	<tr><td>Address:</td><td><%= c.text_field :address %></td></tr>
	<tr><td>Phone:</td><td><%= c.text_field :phone %></td></tr>
	<tr><td>Email:</td><td><%= c.text_field :email %></td></tr>
	<tr><td>Opening hours:</td><td><%= c.text_field :opening_hours %></td></tr>
	<tr><td>Facebook:</td><td><%= c.text_field :facebook %></td></tr>
	<tr><td><%= c.submit "Create contact" %></td></tr>
	</table>
<% end %>
</div>