config/routes.rb
MelodyNelson::Application.routes.draw do
  get "gallery/index"
  get "gallery/editimages"
  get "gallery/edit"
  get "gallery/update"
  get "gallery/new"
  get "gallery/create"
  get "gallery/destroy"
  get "contacts/index"
  get "contacts/new"
  get "contacts/create"
  get "contacts/edit"
  get "contacts/update"
  get "contacts/destroy"
  get "events/index"
  get "events/update"
  get "events/new"
  
  root to: "contacts#index"
  match "login" => "user_sessions#new", via: [:get, :post]
  
  resources :events, :path => "events"
  resources :contacts, :path => "contacts"
  resources :gallery, :path => "gallery"
  resources :photos, :path => "gallery"
  resources :user_sessions
  resources :users
  resources :menus, :path => "menus"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<%= favicon_link_tag %>
	<title>Melody Nelson Bar</title>
	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<link href='http://fonts.googleapis.com/css?family=Special+Elite' rel='stylesheet' type='text/css'>
	<%= csrf_meta_tags %>
	<%= yield :head %>
</head>
<body>
<div id="logo"><%= link_to image_tag("logo.jpg"), contacts_path %></div>
		<div id="sidebar">
			<ul>
				<li><%= link_to "BAR", photos_path, id: ccon("gallery") %></li>
				<li><%= link_to "MENU", menus_path, id: ccon("menus") %></li>
				<li><%= link_to "EVENTS", events_path, id: ccon("events") %></li>
				<li><%= link_to "CONTACT", contacts_path, id: ccon("contacts") %></li>
			<ul>
		</div>
		<div id="logout">
			<% if current_user_session %>
				<%= "Logged in as "+current_user.login %><br />
				<%= link_to "Logout", user_session_path(current_user_session), method: "delete", data: { confirm: 'Are you sure?'} %><br />
				<%= link_to "Change password", edit_user_path(current_user) %>
				<% if current_user.is_admin==1 %>
					<br /><%= link_to "Manage users", users_path %>
				<% end %>
			<% end %>
		</div>
		<div id="content">
			<%= yield %>
		</div>
		<div id="notice"><%= flash[:notice] %></div>
</body>
</html>